// Generated by BUCKLESCRIPT VERSION 4.0.3, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("Login");

function make() {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              return React.createElement("div", {
                          className: "container login_page"
                        }, React.createElement("div", {
                              className: "login-form"
                            }, React.createElement("div", {
                                  className: "main-div"
                                }, React.createElement("div", {
                                      className: "panel"
                                    }, React.createElement("h2", undefined, "Login page"), React.createElement("p", undefined, "Please enter your email and password")), React.createElement("form", {
                                      id: "Login"
                                    }, React.createElement("div", {
                                          className: "form-group"
                                        }, React.createElement("input", {
                                              className: "form-control",
                                              placeholder: "Email Address",
                                              type: "email"
                                            })), React.createElement("div", {
                                          className: "form-group"
                                        }, React.createElement("input", {
                                              className: "form-control",
                                              placeholder: "Password",
                                              type: "password"
                                            })), React.createElement("button", {
                                          className: "btn btn-primary",
                                          type: "submit"
                                        }, "Login")))));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
