// Generated by BUCKLESCRIPT VERSION 4.0.3, PLEASE EDIT WITH CARE
'use strict';


var id = /* record */[/* contents */0];

function getUniqId() {
  id[0] = id[0] + 1 | 0;
  return id[0];
}

exports.getUniqId = getUniqId;
/* No side effect */
