// Generated by BUCKLESCRIPT VERSION 4.0.3, PLEASE EDIT WITH CARE
'use strict';


function toPage(url) {
  var match = url[/* hash */1];
  if (match === "todo") {
    return /* Todo */1;
  } else {
    return /* Login */0;
  }
}

function toUrl(page) {
  if (page) {
    return "todo";
  } else {
    return "dashboard";
  }
}

exports.toPage = toPage;
exports.toUrl = toUrl;
/* No side effect */
